#!/usr/bin/lua

local uci = require('simple-uci').cursor()

local sysconfig = require 'gluon.sysconfig'
local util = require 'gluon.util'
local json = require 'jsonc'

local function get_network_mac(name)
	local board_data = json.load('/etc/board.json')
	local network_data = (board_data or {}).network

	if network_data == nil then
		return nil
	end

	local ifdata = network_data[name] or {}
	return ifdata.macaddr
end

local uplink = uci:get_all('network_gluon-old', 'uplink') or uci:get_all('network_gluon-old', 'wan') or {}
local uplink6 = uci:get_all('network_gluon-old', 'uplink6') or uci:get_all('network_gluon-old', 'wan6') or {}

uci:section('network', 'globals', 'globals', {
	tcp_l3mdev = true,
	udp_l3mdev = true,
	iprule_local_priority = 2000,
})

uci:section('network', 'interface', 'loopback', {
	ifname = 'lo',
	proto = 'static',
	ipaddr = '127.0.0.1',
	netmask = '255.0.0.0',
})

local uplink_proto = 'dhcp'

if sysconfig.gluon_version and uplink.proto ~= nil then
	-- Only restore WAN proto in case this is an upgrade
	uplink_proto = uplink.proto
end

uci:section('network', 'interface', 'uplink', {
	proto = uplink_proto,
	ipaddr = uplink.ipaddr,
	netmask = uplink.netmask,
	gateway = uplink.gateway,
	macaddr = get_network_mac('wan'),
	ifname = util.get_role_interfaces(uci, 'uplink'),
	type = 'bridge',
	igmp_snooping = true,
	multicast_querier = false,
	peerdns = false,
	ip4table = 1,
	policy_rules = false,
	auto = true,
})

uci:section('network', 'interface', 'uplink6', {
	proto = uplink6.proto or 'dhcpv6',
	ip6addr = uplink6.ip6addr,
	ip6gw = uplink6.ip6gw,
	ifname = 'br-uplink',
	peerdns = false,
	ip6table = 1,
	policy_rules = false,
	sourcefilter = false,
	reqprefix = 'no',
})

uci:section('network', 'rule', 'uplink_lookup', {
	mark = '0x01/0x01',
	lookup = 1,
})

uci:section('network', 'rule6', 'uplink6_lookup', {
	mark = '0x01/0x01',
	lookup = 1,
})

uci:section('network', 'route', 'uplink_unreachable', {
	type = 'unreachable',
	interface = 'vrf_uplink',
	target = '0.0.0.0/0',
	gateway = '0.0.0.0',
	table = 1,
	metric = 4278198272,
})

uci:section('network', 'route6', 'uplink6_unreachable', {
	type = 'unreachable',
	interface = 'vrf_uplink',
	target = '::/0',
	gateway = '::',
	table = 1,
	metric = 4278198272,
})

uci:section('network', 'device', nil, {
	type = 'vrf',
	name = 'vrf-uplink',
	table = 1,
	mtu = 1500,
	ports = {'br-uplink', 'wwan0'},
})

uci:section('network', 'interface', 'vrf_uplink', {
	device = 'vrf-uplink',
	proto = 'static',
	ipaddr = '127.0.0.1/8',
	ip6addr = '::1/128',
})

uci:save('network')
